FROM savf/python-27-data-science
ADD cluster_module /cluster_module
ADD dm_lib /cluster_module/dm_lib
WORKDIR /cluster_module
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD ["python", "app.py"]
