FROM savf/python-27-data-science
ADD budget_module /budget_module
ADD dm_lib /budget_module/dm_lib
WORKDIR /budget_module
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD ["python", "app.py"]
