FROM savf/python-27-data-science
ADD jobtype_module /jobtype_module
ADD dm_lib /jobtype_module/dm_lib
WORKDIR /jobtype_module
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD ["python", "app.py"]
