FROM savf/python-27-data-science
ADD knn_module /knn_module
ADD dm_lib /knn_module/dm_lib
WORKDIR /knn_module
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD ["python", "app.py"]
